[package]
name = "russtv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deflate = "1.0.0"
easyfft = "0.3.5"
rodio = "0.17.1"
spectrum-analyzer = "1.4.0"
